### ISSUE TITLE
Determine server-side tech stack

### ISSUE THREAD

**Issue by mscottford** [andreagoulet/callmyreps#11]
It's pretty clear that this is going to require some form of a server-side component, and that brings with it the question about what we should choose for that.

Here are some choices:
* Ruby
* .NET Core
* Node
* PHP
* JVM

**Comment by chris-allnutt** [comment]
My vote is for Ruby or Node in no particular order.  While I'm a huge fan of .Net .Net Core even at rc2 it seems to still be in some state of flux right now and could make upgrading in the future difficult.

**Comment by mscottford** [comment]
I also realized that I left Elixr off the list.

**Comment by andreagoulet** [comment]
I'm most comfortable with ruby, but am happy to learn/adapt to whatever we decide is the best fit.

**Comment by chris-allnutt** [comment]
I'd be totally onboard for Elixir too.  Been wanting to work with it but haven't yet.

**Comment by andreagoulet** [comment]
Maybe we could even get @kiere to join us if we picked Elixir. ;)

**Comment by kiere** [comment]
😄 Distributed computing FTW

**Comment by mscottford** [comment]
I've been reading up on Node frameworks, and I'm impressed by [Feathers](http://feathersjs.com/). 

Here's a list of the things that I think it does well.
- Opinionated, quick and consistent api for that is available via REST and WebSockets.
- Modular
- Many different modules already built out (including ones for sending text messages via Twilio, auth via Facebook, Twitter and many others). 

I also found some [sample code](https://gist.github.com/swarthout/9c33b718e9d70d068378d221b1127900) for handling Apple and Google Play notifications. General push notification support hasn't been built into the tooling so far, but it's on the general roadmap. It also looks easy enough to pull off without it.

**Comment by tonygambone** [comment]
I'd love to be involved in this too, so rather than lurk I'll chime in :)

I haven't used feathers but I hear good things... one thought is that it might encourage the use of React-Native over in #9. There's a [feathers iOS client](https://github.com/feathersjs/feathers-ios) that's not ready yet.  The app could probably speak raw HTTP or websockets but it'd be nicer to work with the client library.

Any thoughts on data storage? Looks like feathers can talk to anything but uses Redis or MongoDB for [syncing events](https://github.com/feathersjs/feathers-sync).

**Comment by andreagoulet** [comment]
Yay! Welcome @tonygambone! So glad you're here.

**Comment by jrhodes621** [comment]
My vote is NodeJS and MongoDB; I see the backend being mostly an API to serve various clients with a fairly simple data model, Node/Mongo does this pretty well; I've used Express and SailsJS with some sucess; Feather looks like it would suffice and may be better tailored to creating simple apis

**Comment by chris-allnutt** [comment]
@andreagoulet I think we can close this now @tonygambone has a PR up for this #21

**Comment by andreagoulet** [comment]
Agreed. Thanks @chris-allnutt
