### ISSUE TITLE
Determine User Authentication Methods

### ISSUE THREAD

**Issue by chris-allnutt** [andreagoulet/callmyreps#12]
Do we roll our own, or do we leverage auth api's like Facebook, Google, Twitter etc..  Usually you can find a library that can handle all these in one go.

**Comment by andreagoulet** [comment]
I'd think libraries are the way to go. Speed to market is our focus right now.

**Comment by chris-allnutt** [comment]
@andreagoulet I'm going to close this issue for now, we can review all the tech stack tickets once they're completed and then make some more concrete decisions on libraries we'll identify for usage.

**Comment by andreagoulet** [comment]
Makes sense. I'll work on putting together a product roadmap. I think that will really help everyone organize tasks.
