### ISSUE TITLE
Determine App Technology Stack

### ISSUE THREAD

**Issue by chris-allnutt** [andreagoulet/callmyreps#9]
What technology should we use?
A few things to consider:
What platform do we want to support initially Apple/Android?

If we decide to go cross platform (think Xamarin, RubyMotion, CoronaSDK, PhoneGap, Unity, <insert preferred framework here> etc... What do people have experience with?

If we decide to go native with both applications, do we have people here who have experience with Android and IOS development?

This isn't an immediate need, story boards, personas, copy(for our objectives) are more important but I don't want this to fall on the wayside.

**Comment by andreagoulet** [comment]
I know @mscottford has some opinions about the tech stack. 

I was thinking cross platform to start and then investing in native builds later after MVP and beta stages.

**Comment by mscottford** [comment]
I think that if we have to only target one mobile platform at first, I would suggest it be iOS, and I wouldn't want Android and Windows Phone to be far behind.

I was playing with React-Native last night. I think that could be a decent tool to use, but I'm not experienced enough with it to be productive from the ground up. I'm open to other suggestions as well.

**Comment by chris-allnutt** [comment]
@mscottford react native should be fine.  If we don't want to worry about the design too much in the beginning there are also material-ui implementations for a decent user interface https://github.com/xotahal/react-native-material-ui

I'll state now tho that I'm not a huge fan of react, but used it in my past 2 production projects.

**Comment by mscottford** [comment]
@chris-allnutt: If you have reservations against react-native, I think it would be worth chatting about those before we get started. The first decision is often the hardest to change later. :)

**Comment by chris-allnutt** [comment]
@mscottford  Sounds good it also appears from the MVP discussion @andreagoulet wants to take a strong lead in the MVP development.  Since she's at the helm we should make sure it's a technology she feels comfortable with as well.  I'm more than happy to help with whatever language is used so long as it's not VB6 or Java ;)

**Comment by andreagoulet** [comment]
I haven't used React, but I'm comfortable learning whatever the right stack is. 

We're looking for something that's: 
- cross-platform 
- relatively well known 
- well documented 
- provide experience that "feels" native
- cost/licensing

I'm most comfortable with Ruby on Rails, so if I were being pragmatic, I'd go with RubyMotion. I have to admit, there's an adventurous part of me wants to go with Swift and figure out how to do the whole thing server-side, but looking at the above criteria, I don't think that's the right choice.

**Comment by chris-allnutt** [comment]
I believe the only limitation of RubyMotion is that it requires devs to be using a mac.  Swift tho carries the same limitation.

All this being said while the long term goal may be multi-platform there's also a strong case to be made for doing one platform and doing it really well so Swift on iOS wouldn't be a stretch.  @andreagoulet I think you'd find swift to feel very natural.  Also they just released a fairly major update to the framework.

**Comment by andreagoulet** [comment]
I really really really like Swift from what I've done with it so far. Plus, that's a really good point about picking one platform and doing it well. 

If I think about the mission of the project, I'm worried that if we limited it to iOS, we'd be leaving out a lot of citizens and the idea is getting this out and useable as fast as possible to as many people as possible. I want to be careful that we don't let perfect get in the way of good.

**Comment by chris-allnutt** [comment]
@andreagoulet that also depends on how much logic we decide to encapsulate in the application vs the API.  The API will be handset agnostic, so if the Mobile app is primarily an interface to API calls we won't have too much of a problem recreating that interface on other platforms.  A kind of iterative approach could be.  V1 is iOS using Swift.  We then take our lessons learned and use it to select a cross platform (Andorid, Windows, iOS) option that we can recreate it in.  If our goal is to get something together quickly single target may be the way to go.  With github we can even create additional repositories for each of the endeavors callmyreps-ios, callmyreps-api, callmyreps-crossplatform-mobile etc...

**Comment by kiere** [comment]
Just FYI, you can develop Swift on Linux now... assuming you are talking about server-side frameworks like Vapor.  If you are doing iOS dev in Swift, you'll want a Mac for sure.  There was talk of Google adopting Swift for Android development, but last I heard, their reasons for that went away, so it's probably dead in the water now.

**Comment by andreagoulet** [comment]
I'd like to make a decision on this quickly so we can start building. I'd like to get this out to as many people as possible as quickly as possible. Given that as our first mission, my instinct is that RubyMotion is the way to go, at least for the MVP. I don't see that as a long-term solution and I would like to continue the discussions around building natively for V1. For now, let's get something up fast. At least for the MVP stage, where speed to market is our biggest concern, it's probably better to go with something familiar.

**Comment by jrhodes621** [comment]
Just my two cents as far how I would look at it, IMO the choice should come down to what expertise we have as a team; personally my expertise is in Swift and I would shy away from using Ruby Motion for the MVP because I could get it done faster in Swift, but if there is some expertise in Ruby Motion on the team that's is also a good direction to go; if we have an expert I would love to be involved in working with Ruby Motion, just not something I would jump into by myself, from what I have seen both can result in an engaging app that will delight users and ultimately gets the app used/downloaded

**Comment by chris-allnutt** [comment]
@jrhodes621 I don't believe we currently have any RubyMotion experience.  Between your comment here and @andreagoulet's above I would like to propose we move forward with Swift and target iOS for our initial mobile client.

@andreagoulet thoughts?

Personally I pride myself on being polygot, and I'm fairly sure @mscottford does too so we'll feel comfortable contributing to anything.

**Comment by andreagoulet** [comment]
I think we all pride ourselves on being polyglots @chris-allnut. :) 

@chris-allnutt and @jrhodes621: Help me understand the speed that you feel we could get a Swift app out. Are we talking days? Weeks? Months?  How confident are you in that answer? 20%? 80%? 

If we do start in Swift/iOS, how fast could we get it to android and have a web version out? 

Sounds like RubyMotion is not the right path. I'd like to put together a side by side comparison between Swift and React Native. It sounds like we're closing in on those two options. @mscottford @kiere @tonygambone I'd like to hear your thoughts here. Let's plan on having a decision made by the end of the day so we can start building.

**Comment by mscottford** [comment]
> the choice should come down to what expertise we have as a team

I think that for the MVP that's a very good way to look at things. I have some RubyMotion experience, but I dislike the cost of that tool. If we have some Swift experience on the team, then it's  sounding like that could be the best thing to just get _something_ started. I think picking a cross-platform solution is going to be best for the long term, which leans me towards react-native.

Since I have the same amount of experience with both, my vote is react-native.

**Comment by jrhodes621** [comment]
@andreagoulet my typical response to a time estimate at this point would be something along the lines of "let's talk about the features we want" so this is a guess, given what's in my head, 4 - 6 weeks +/- a couple weeks seems like a decent ballpark for the MVP, thoughts??

**Comment by andreagoulet** [comment]
@jrhodes621 that's a fair point. I'll spend some time this weekend scoping out the MVP feature set and putting together the product roadmap. No pressure to try to make things faster than they would naturally be and I think your estimate is spot on, especially given that most of us are doing this as a side gig and have other commitments. 

The question I'm trying to answer is this: since speed to market is our biggest need, is there a significant difference in the time it would take to develop between Swift and React Native? 

So for example, if it would take 2 days to build the same thing in Swift, would it take 2 months in React Native given the same MVP feature set? In that case, I think Swift would win out. 

On the other hand, if they're relatively the same in terms of development time (both would take 6 weeks), React Native would be a better choice for our needs because we could go cross-platform and get the biggest potential user base. 

Once we get that answered, I think we'll be good to move forward. :)

**Comment by tonygambone** [comment]
I haven't done any native mobile dev to speak of, so grain of salt, etc.  I use an Android device and don't own a Mac.  I'd probably leave the MVP app dev to someone else and work on the server instead, and maybe a basic mobile-ready web interface if there's time.  But if you still want my vote, it's probably React-Native :)

**Comment by jrhodes621** [comment]
Overall, I don't think there would be a significant difference.  I would expect the time to implement a feature (a well-defined one) would be relatively the same (for experienced developers, which we have!).  A feature in Swift that take a couple day would maybe take couple days in React in some cases or maybe 3 or 4 days sometimes but you will probably have the reverse happen, where a feature takes 2 days in Swift takes only 1 day in React.  Hopefully it averages out over the long run.  But nothing crazy where it takes a couple months.  Regardless I would think React or Swift still leaves things in the 4-6 +/- a couple weeks ballpark or whatever project estimate is correct. @mscottford @chris-allnutt what are your thoughts?

**Comment by jrhodes621** [comment]
So this is totally my personal preference, from what I can see in the docs and I found this to be true with the little React experience I have, you end up having to hardcode a lot of views/html in code like this:

```
#render() {
    return (
      <Text>Hello world!</Text>
    );
  }
```

Obviously you can get much more complex than this.  I see things like this as painful and error prone, difficult to debug, etc.  Anyway just saying, maybe others have better approaches to limit doing this and can school me if we go with React. Thanks for listening...

**Comment by tonygambone** [comment]
It's true, but there's power there also - for instance you can define a whole structure of nested components, with each one of those being a self contained chunk of code responsible for rendering itself in response to data changes, and delegating the rendering of its own children.  At least on the web side, there is a browser extension for inspecting the React component tree - not sure how the tooling is for mobile.  The JSX syntax is really just a shorthand for more long-winded, boilerplate-y JavaScript.

You're also making React fully aware of the structure of the app so it can selectively re-render the parts that change based on events - so for instance, if a parent component does not have any changes to its state, then React will skip the entire rendering process for it and its children.

**Comment by andreagoulet** [comment]
I love the thoughtful discussion here. I'm really glad everyone shared their point of view. Thank you! This really helped me make sense of the pros and cons. 

No solution will ever be perfect, but it sounds like for our purposes, React Native is the way to go. I'll go ahead and mark this issue as closed. Thanks again, y'all!

**Comment by kiere** [comment]
Sorry to chime in late.  I was stuck in traffic on the way to BWI.

In my experience, the cross-platform tools work well to get a basic MVP out the door, but quickly break down as you need to add more complex features.  You'll find yourself dropping into the low-level features of each OS to get the meat of the feature built.  I think you can use it to work out the flow and UI, and as this process progresses, those developers with native Swift/Cocoa Touch and Android experience can start forming the full-blown native versions of the mobile clients from the work done in React Native.

In the meantime, there are always fun things to do.  At my last job, I was experimenting with setting up a Jenkins server that pushed the native builds into Amazon Device Farm so each build would be tested on a whole suite of real device/OS combinations.  I never got past the initial setup of the Jenkins server though.  I always use hosted CI solutions like Semaphore/Travis/Circle CI.  No Jenkins expertise here.  So I was in the middle of learning that when the project got cancelled.

Just my two cents. 😄  I'll be on a plane all day tomorrow but I'll catch up with all the rest of the conversations on Sunday.

**Comment by jrhodes621** [comment]
@kiere good point; I tend to agree with you on cross-platform tools, yet they are always getting better so I try not to discount them, I've constantly found myself hitting some roadblock or having to puting in some Herculean effort in to get past something that the tool doesn't do well; hopefully we can stay clear of those for the MVP, I am interested to see how this evolves
